#deploy.yml
- hosts: cluster
  become: yes
  tasks:

    - name: "Remove old JAR"
      file:
        state: "absent"
        path: "sa"

    - name: "Copy new JAR"
      copy:
        src: "."
        dest: "dsa"
